## Working with JSON

In [6]:
import pandas as pd

In [2]:
pd.read_json("../datasets/train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
#Edi URL ma xa then just paste the url
url = ""
pd.read_json(url)

## Working with SQL

To convert sql file(MySQL) to dataframe using pandas you need a library

```bash
pip install mysql-connector-python
```
Working:
```py
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="your_password",
    database="world"
)

cursor = conn.cursor()
cursor.execute("SELECT * FROM city")

rows = cursor.fetchall()
print(rows)

cursor.close()
conn.close()
```


For a file of sql but for postgres
```bash
pip install "psycopg[binary]"
```
Working: 
```py
import psycopg

conn = psycopg.connect(
    host="localhost",
    dbname="world_db",
    user="postgres",
    password="your_password"
)

cursor = conn.cursor()
cursor.execute("SELECT * FROM world.city")

rows = cursor.fetchall()
print(rows)

cursor.close()
conn.close()
```

In [ ]:
import psycopg

conn = psycopg.connect(
    host = "localhost",
    dbname ="world",
    user="postgres",
    password="Everyoneknows01"
)
cursor = conn.cursor()

# cursor.close()
# conn.close()

In [32]:
conn.rollback()

with conn.cursor() as cur:
    cur.execute("Set search_path to world")
    
conn.commit()

In [ ]:
df = pd.read_sql_query("Select * from city where countrycode like 'NP%' ", conn)

C:\Users\Asim\AppData\Local\Temp\ipykernel_41584\1084422540.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("Select * from city where countrycode like 'NP%' ", conn)

,id,name,countrycode,district,population
0,2729,Kathmandu,NPL,Central,591835
1,2730,Biratnagar,NPL,Eastern,157764
2,2731,Pokhara,NPL,Western,146318
3,2732,Lalitapur,NPL,Central,145847
4,2733,Birgunj,NPL,Central,90639

In [ ]:
cursor.close()
conn.close()

```python

```