In [ ]:
import pandas as pd
import requests
import os
from dotenv import load_dotenv

load_dotenv()
MY_API_KEY = os.getenv("TMDB_API_KEY")

e77c047ce028a2b9aaa62535fec79cdc

In [ ]:
response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key={MY_API_KEY}&page=1")
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/caBIySpwuFi2i7ynvHIlnxJLOdN.jpg',
   'genre_ids': [16, 28, 12, 18],
   'id': 1560520,
   'title': 'Batman: Knightfall Part 1: Knightfall',
   'original_language': 'en',
   'original_title': 'Batman: Knightfall Part 1: Knightfall',
   'overview': 'Arkham Asylum has been destroyed, and all its inmates have been unleashed upon Gotham City. As Batman races to round up some of his greatest enemies, he is pushed to his physical and mental limits and into a final confrontation with a new threat: the man called Bane!',
   'popularity': 43.2003,
   'poster_path': '/360qdtu2hLnqMu8SVHMywn420w1.jpg',
   'release_date': '2026-06-23',
   'softcore': False,
   'video': False,
   'vote_average': 9.099,
   'vote_count': 470},
  {'adult': False,
   'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
   'genre_ids': [16, 12, 14, 28],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 70.6293,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.053,
   'vote_count': 1355},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 48.7525,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.851,
   'vote_count': 2262},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 12.7115,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.823,
   'vote_count': 403},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 54.3615,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.806,
   'vote_count': 2309},
  {'adult': False,
   'backdrop_path': '/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg',
   'genre_ids': [80, 28, 53],
   'id': 1621552,
   'title': 'Facing El Chapo',
   'original_language': 'es',
   'original_title': 'La captura',
   'overview': 'Two Mexican officers must survive the final hours of their shift after crossing a ruthless cartel boss.',
   'popularity': 44.4715,
   'poster_path': '/alpf5v4UqSFawPmG9RX03Or4BDk.jpg',
   'release_date': '2026-08-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.782,
   'vote_count': 948},
  {'adult': False,
   'backdrop_path': '/pNjh59JSxChQktamG3LMp9ZoQzp.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 55.5316,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.733,
   'vote_count': 31619},
  {'adult': False,
   'backdrop_path': '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 55.3321,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.689,
   'vote_count': 23790},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 79.9864,
   'poster_path': '/iOb2fjXLbpJgyQXe46n1WtGCnaa.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.634,
   'vote_count': 8380},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 44.8052,
   'poster_path': '/dueFqKLvjftnELZaGYwY7xinfaI.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.606,
   'vote_count': 4595},
  {'adult': False,
   'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
   'genre_ids': [18, 10749],
   'id': 1232449,
   'title': 'Young Hearts',
   'original_language': 'nl',
   'original_title': 'Young Hearts',
   'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
   'popularity': 16.7472,
   'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
   'release_date': '2024-10-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 329},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 28.8802,
   'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.575,
   'vote_count': 10494},
  {'adult': False,
   'backdrop_path': '/pGzqRKrYeK4LogoysNro0vG8d8N.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 32.129,
   'poster_path': '/8a1lJs7mFyGhGhZZDT1azJUoQiZ.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.573,
   'vote_count': 14486},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 41.3759,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 18061},
  {'adult': False,
   'backdrop_path': '/xA6AM5MvEkieZKlv1Tn3sN23I7i.jpg',
   'genre_ids': [28, 18, 10749],
   'id': 1630423,
   'title': 'My Dearest Assassin',
   'original_language': 'th',
   'original_title': 'เลือดรักนักฆ่า',
   'overview': 'Hunted for her rare blood type, a caged woman vows to fight alongside the assassin she loves to protect their future when an old enemy resurfaces.',
   'popularity': 16.8884,
   'poster_path': '/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg',
   'release_date': '2026-05-06',
   'softcore': False,
   'video': False,
   'vote_average': 8.562,
   'vote_count': 313},
  {'adult': False,
   'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 34.3836,
   'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 1246},
  {'adult': False,
   'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
   'genre_ids': [28, 53, 80],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 52.5586,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.538,
   'vote_count': 37004},
  {'adult': False,
   'backdrop_path': '/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 58.429,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.537,
   'vote_count': 19073},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 41.0926,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 19996},
  {'adult': False,
   'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 65.7225,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.505,
   'vote_count': 27615}],
 'total_pages': 567,
 'total_results': 11334}

In [16]:
df = pd.DataFrame(response.json()['results'])
df = df[['id','title','vote_average','vote_count','popularity','release_date']]
df

,id,title,vote_average,vote_count,popularity,release_date
0,1560520,Batman: Knightfall Part 1: Knightfall,9.099,470,43.2003,2026-06-23
1,980431,Avatar Aang: The Last Airbender,9.053,1355,70.6293,2026-07-24
2,1007757,Swapped,8.851,2262,48.7525,2026-05-01
3,1632181,Accidental Partners,8.823,403,12.7115,2026-03-12
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,8.806,2309,54.3615,2025-07-18
5,1621552,Facing El Chapo,8.782,948,44.4715,2026-08-21
6,278,The Shawshank Redemption,8.733,31619,55.5316,1994-09-23
7,238,The Godfather,8.689,23790,55.3321,1972-03-14
8,687163,Project Hail Mary,8.634,8380,79.9864,2026-03-15
9,936075,Michael,8.606,4595,44.8052,2026-04-22
10,1232449,Young Hearts,8.600,329,16.7472,2024-10-26
11,389,12 Angry Men,8.575,10494,28.8802,1957-04-10
12,240,The Godfather Part II,8.573,14486,32.1290,1974-12-20
13,424,Schindler's List,8.570,18061,41.3759,1993-12-15
14,1630423,My Dearest Assassin,8.562,313,16.8884,2026-05-06
15,1218925,Chainsaw Man - The Movie: Reze Arc,8.500,1246,34.3836,2025-09-19
16,155,The Dark Knight,8.538,37004,52.5586,2008-07-16
17,129,Spirited Away,8.537,19073,58.4290,2001-07-20
18,497,The Green Mile,8.506,19996,41.0926,1999-12-10
19,122,The Lord of the Rings: The Return of the King,8.505,27615,65.7225,2003-12-17

In [21]:
df = pd.DataFrame(response.json()['results'])[['id','title','vote_average','vote_count','popularity','release_date']]
df

,id,title,vote_average,vote_count,popularity,release_date
0,1560520,Batman: Knightfall Part 1: Knightfall,9.099,470,43.2003,2026-06-23
1,980431,Avatar Aang: The Last Airbender,9.053,1355,70.6293,2026-07-24
2,1007757,Swapped,8.851,2262,48.7525,2026-05-01
3,1632181,Accidental Partners,8.823,403,12.7115,2026-03-12
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,8.806,2309,54.3615,2025-07-18
5,1621552,Facing El Chapo,8.782,948,44.4715,2026-08-21
6,278,The Shawshank Redemption,8.733,31619,55.5316,1994-09-23
7,238,The Godfather,8.689,23790,55.3321,1972-03-14
8,687163,Project Hail Mary,8.634,8380,79.9864,2026-03-15
9,936075,Michael,8.606,4595,44.8052,2026-04-22
10,1232449,Young Hearts,8.600,329,16.7472,2024-10-26
11,389,12 Angry Men,8.575,10494,28.8802,1957-04-10
12,240,The Godfather Part II,8.573,14486,32.1290,1974-12-20
13,424,Schindler's List,8.570,18061,41.3759,1993-12-15
14,1630423,My Dearest Assassin,8.562,313,16.8884,2026-05-06
15,1218925,Chainsaw Man - The Movie: Reze Arc,8.500,1246,34.3836,2025-09-19
16,155,The Dark Knight,8.538,37004,52.5586,2008-07-16
17,129,Spirited Away,8.537,19073,58.4290,2001-07-20
18,497,The Green Mile,8.506,19996,41.0926,1999-12-10
19,122,The Lord of the Rings: The Return of the King,8.505,27615,65.7225,2003-12-17

In [29]:
df = pd.DataFrame()
dfs=[]
for i in range(1,501):
    response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key={MY_API_KEY}&page={i}")
    
    if response.status_code != 200:
        print(f"Request failed on page {i}")
        print(response.status_code)
        print(response.json())
        break
    
    temp_df= pd.DataFrame(response.json()['results'])[['id','title','vote_average','vote_count','popularity','release_date']]
    dfs.append(temp_df)
    
df = pd.concat(dfs, ignore_index=True)
print(df.head())
print(df.shape)

        id                                           title  vote_average  \
0  1560520           Batman: Knightfall Part 1: Knightfall         9.099
1   980431                 Avatar Aang: The Last Airbender         9.053
2  1007757                                         Swapped         8.851
3  1632181                             Accidental Partners         8.823
4  1311031  Demon Slayer: Kimetsu no Yaiba Infinity Castle         8.806

   vote_count  popularity release_date
0         470     43.2003   2026-06-23
1        1355     70.6293   2026-07-24
2        2262     48.7525   2026-05-01
3         403     12.7115   2026-03-12
4        2309     54.3615   2025-07-18
(10000, 6)

In [31]:
df.to_csv("../datasets/movies.csv")