Encoding numerical to Categorical 

- Discretization (Binning)

- Binarization

### Binning

- create a set of contiguous intervals (bins) that span the range of variable's value.

Divided into three types 
 - Unsupervised binning
 - Supervised binning
  - Custom binning

In [1]:
import pandas as pd 
import numpy as np

In [2]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv("../datasets/titanic_dataset.csv",  usecols=['Age','Fare','Survived'])
df.sample(5)

     Survived   Age     Fare
661         0  40.0   7.2250
526         1  50.0  10.5000
500         0  17.0   8.6625
315         1  26.0   7.8542
652         0  21.0   8.4333

In [7]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [8]:
df.shape

(891, 3)

In [9]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2, random_state=42
)
X_train

           Age      Fare
331  45.500000   28.5000
733  23.000000   13.0000
382  32.000000    7.9250
704  26.000000    7.8542
813   6.000000   31.2750
..         ...       ...
106  21.000000    7.6500
270  29.699118   31.0000
860  41.000000   14.1083
435  14.000000  120.0000
102  21.000000   77.2875

[712 rows x 2 columns]

In [11]:
clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [12]:
accuracy_score(y_test, y_pred)

0.6871508379888268

In [13]:
clf = DecisionTreeClassifier()
np.mean(cross_val_score(clf, X, y, cv = 10, scoring='accuracy'))

np.float64(0.6666791510611735)

Applying Binning

In [14]:
kbin_age = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')

In [18]:
trf = ColumnTransformer(
    [
        ('first', kbin_age, [0]),
        ('second', kbin_fare, [1])
    ], remainder='passthrough'
).set_output(transform='pandas')

In [19]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

d:\Projects\Machine-Learning\venv\Lib\site-packages\sklearn\preprocessing\_discretization.py:385: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(

In [27]:
trf.named_transformers_['first'].bin_edges_

array([array([ 0.42      , 16.        , 21.        , 24.        , 28.        ,
              29.69911765, 32.        , 38.        , 47.        , 80.        ])],
      dtype=object)

In [28]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf, y_train)
y_pred2 = clf.predict(X_test_trf)

In [29]:
accuracy_score(y_test, y_pred2)

0.6871508379888268

In [30]:
clf = DecisionTreeClassifier()
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(clf, X_trf, y, cv = 10, scoring='accuracy'))

d:\Projects\Machine-Learning\venv\Lib\site-packages\sklearn\preprocessing\_discretization.py:385: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(

np.float64(0.6825468164794009)

### Binarization

- continuous value into binary (0 or 1)
- special case of discretization

Binarizer class is used from scikit learn